"""Task 1, Step 3: Shape vs. Texture evaluation.

Runs every trained head (+ CLIP zero-shot) on the cue-conflict images
generated by make_cue_conflicts.py, classifies each prediction as
content/shape, style/texture, or other, and reports shape bias and coverage
per model. Also saves a small sample of agreements/disagreements/failures
for the report's required qualitative evidence.

Requires make_cue_conflicts.py and run_task1_clean_baseline.py to have been
run first (uses the saved heads and the generated cue-conflict images).

Usage (from inside task1/):
    python scripts/run_task1_shape_texture.py --config configs/clean_baseline.yaml
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np
import torch
import torch.nn.functional as F
import yaml
from torch.utils.data import DataLoader

sys.path.append(str(Path(__file__).resolve().parents[1] / "data"))
sys.path.append(str(Path(__file__).resolve().parents[1] / "models"))
sys.path.append(str(Path(__file__).resolve().parents[1] / "analysis"))
sys.path.append(str(Path(__file__).resolve().parents[2]))

from dataset import build_split_datasets  # noqa: E402
from cue_conflict_dataset import CueConflictDataset  # noqa: E402
from backbones import build_backbone, LinearHead  # noqa: E402
from checkpoints import load_head_state  # noqa: E402
from evaluate_bias import shape_bias_and_coverage  # noqa: E402
from common.seed import set_seed  # noqa: E402


def run_backbone_on_conflicts(backbone, head_or_none, conflict_ds, device, is_zero_shot=False):
    """Returns (preds, content_labels, style_labels, filenames) as numpy arrays/lists."""
    loader = DataLoader(
        conflict_ds, batch_size=32, shuffle=False,
        collate_fn=lambda batch: (
            torch.stack([backbone.preprocess(img) for img, _, _, _ in batch]),
            torch.tensor([c for _, c, _, _ in batch]),
            torch.tensor([s for _, _, s, _ in batch]),
            [f for _, _, _, f in batch],
        ),
    )
    all_preds, all_content, all_style, all_fnames = [], [], [], []
    with torch.no_grad():
        for imgs, content_labels, style_labels, fnames in loader:
            imgs = imgs.to(device)
            if is_zero_shot:
                probs = backbone.zero_shot_predict(imgs).cpu()
            else:
                feats = backbone.extract_features(imgs)
                logits = head_or_none(feats)
                probs = F.softmax(logits, dim=1).cpu()
            preds = probs.argmax(dim=1).numpy()
            all_preds.append(preds)
            all_content.append(content_labels.numpy())
            all_style.append(style_labels.numpy())
            all_fnames.extend(fnames)
    return (np.concatenate(all_preds), np.concatenate(all_content),
            np.concatenate(all_style), all_fnames)


def sample_failures_and_agreements(preds, content, style, fnames, class_names, n_each=3):
    agreements, disagreements, failures = [], [], []
    for i in range(len(preds)):
        record = {
            "filename": fnames[i],
            "content_class": class_names[content[i]],
            "style_class": class_names[style[i]],
            "predicted_class": class_names[preds[i]],
        }
        if preds[i] == content[i]:
            agreements.append(record)
        elif preds[i] == style[i]:
            disagreements.append(record)
        else:
            failures.append(record)
    return {
        "sample_agreements": agreements[:n_each],
        "sample_disagreements": disagreements[:n_each],
        "sample_other_failures": failures[:n_each],
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", required=True)
    ap.add_argument("--manifest", default="results/cue_conflicts_manifest.json")
    ap.add_argument("--images-dir", default="data_raw/cue_conflicts")
    ap.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    args = ap.parse_args()

    cfg = yaml.safe_load(Path(args.config).read_text())
    set_seed(cfg["seed"])
    results_dir = str(Path(cfg["output"]["results_json"]).parent)

    _, _, eval_ds = build_split_datasets(cfg["dataset"], cfg["data_root"], cfg["splits_path"])
    class_names = eval_ds.class_names

    conflict_ds = CueConflictDataset(args.manifest, args.images_dir)
    print(f"[shape_texture] loaded {len(conflict_ds)} cue-conflict images")

    results = {"dataset": cfg["dataset"], "seed": cfg["seed"], "models": {}}

    for name in cfg["backbones"]:
        print(f"\n[shape_texture] === {name} ===")
        backbone = build_backbone(name, class_names=class_names if name == "clip_vit_b_32" else None)
        backbone.to(args.device)

        head = LinearHead(backbone.feature_dim, len(class_names))
        head.load_state_dict(load_head_state(results_dir, name))
        head.to(args.device).eval()

        preds, content, style, fnames = run_backbone_on_conflicts(
            backbone, head, conflict_ds, args.device, is_zero_shot=False
        )
        metrics = shape_bias_and_coverage(preds, content, style)
        samples = sample_failures_and_agreements(preds, content, style, fnames, class_names)
        print(f"  [{name} head] shape_bias={metrics['shape_bias_pct']:.1f}% "
              f"coverage={metrics['coverage_pct']:.1f}% "
              f"(n_shape={metrics['n_shape']} n_texture={metrics['n_texture']} n_other={metrics['n_other']})")
        results["models"][name] = {**metrics, **samples}

        if name == "clip_vit_b_32":
            preds_zs, content_zs, style_zs, fnames_zs = run_backbone_on_conflicts(
                backbone, None, conflict_ds, args.device, is_zero_shot=True
            )
            metrics_zs = shape_bias_and_coverage(preds_zs, content_zs, style_zs)
            samples_zs = sample_failures_and_agreements(preds_zs, content_zs, style_zs, fnames_zs, class_names)
            print(f"  [clip zero-shot] shape_bias={metrics_zs['shape_bias_pct']:.1f}% "
                  f"coverage={metrics_zs['coverage_pct']:.1f}%")
            results["models"]["clip_zero_shot"] = {**metrics_zs, **samples_zs}

    out_path = Path(results_dir) / "shape_texture_seed6304.json"
    out_path.write_text(json.dumps(results, indent=2))
    print(f"\n[shape_texture] wrote {out_path}")


if __name__ == "__main__":
    main()
